$e:: Send {е}
$r:: Send {р}
$t:: Send {т}
$y:: Send {и}
$u:: Send {у}
$i:: Send {і}
$o:: Send {о}
$p:: Send {п}
$a:: Send {а}
$s:: Send {с}
$d:: Send {д}
$f:: Send {ф}
$g:: Send {щ}
$h:: Send {г}
$j:: Send {й}
$k:: Send {к}
$l:: Send {л}
$z:: Send {з}
$x:: Send {х}
$c:: Send {ц}
$v:: Send {в}
$b:: Send {б}
$n:: Send {н}
$m:: Send {м}
$q:: Send {я}
$':: Send {є}
$/:: Send {ю}
$]:: Send {ї}
$;:: Send {ж}
$[:: Send {ч}
$w:: Send {ш}
$\:: Send {ь}
$.:: Send {ы}

$+E:: Send {Е}
$+R:: Send {Р}
$+T:: Send {Т}
$+Y:: Send {И}
$+U:: Send {У}
$+I:: Send {І}
$+O:: Send {О}
$+P:: Send {П}
$+A:: Send {А}
$+S:: Send {С}
$+D:: Send {Д}
$+F:: Send {Ф}
$+G:: Send {Щ}
$+H:: Send {Г}
$+J:: Send {Й}
$+K:: Send {К}
$+L:: Send {Л}
$+Z:: Send {З}
$+X:: Send {Х}
$+C:: Send {Ц}
$+V:: Send {В}
$+B:: Send {Б}
$+N:: Send {Н}
$+M:: Send {М}
$+Q:: Send {Я}
$+':: Send {Є}
$+/:: Send {Ю}
$+]:: Send {Ї}
$+;:: Send {Ж}
$+[:: Send {Ч}
$+W:: Send {Ш}
$+&:: Send {?}
